### ISSUE TITLE
s6-supervise run file doesn't terminate if rutorrent crashes

### ISSUE THREAD

**Issue by leonixyz** [linuxserver/docker-rutorrent-armhf#22]
Hello,

this image is great, thank you for your effort.

I noticed that [the s6-supervise run file for rtorrent](https://github.com/linuxserver/docker-rutorrent-armhf/blob/master/root/etc/services.d/rutorrent/run) basically do just two things:

1. it starts a screen session with rtorrent
2. prints the rtorrent log file to stdout 

I run into a problem when rtorrent for some reason crashes. The screen session terminates, but the tail command is still executing. Therefore, the supervise script never terminates and s6-supervise doesn't restarts rtorrent. nginx keeps working and but the torrent service is down.

Could you please fix it by splitting into two services rtorrent and the log-printing?
If you do so, you don't even need to use screen, because the script is forked automatically by s6-supervise.

If you want I can do a pull request, but I'm not very expert.

thanks in advance

**Comment by TheLonelyGhost** [comment]
Experiencing the same issue here. rtorrent keeps crashing, such as when trying to remove a torrent and all files downloaded, and rutorrent just panics since rtorrent isn't coming back up. It has gotten to the point where I now need to have an ssh client installed on my phone to restart the container in order to then restart the rtorrent service reliably.

From the looks of the file you linked, it looks like it's a typo with the run file for rtorrent. `tail` requires a `--pid` flag to work as intended here. PR to follow.

**Comment by homerr** [comment]
Sorry for how long this was open. We've now re-written this container and released it multi-arch as linuxserver/rutorrent (the repo is https://github.com/linuxserver/docker-rutorrent )

I hope the changes made in the container here, address these problems.
